export const PEOPLE_SEARCH_REQUEST = 'PEOPLE_SEARCH_REQUEST';
export const PEOPLE_SEARCH_SUCCESS = 'PEOPLE_SEARCH_SUCCESS';
export const PEOPLE_SEARCH_FAILURE = 'PEOPLE_SEARCH_FAILURE';

export const PERSON_REQUEST = 'PERSON_REQUEST';
export const PERSON_SUCCESS = 'PERSON_SUCCESS';
export const PERSON_FAILURE = 'PERSON_FAILURE';

export const PEOPLE_ROOT_URL = process.env.REACT_APP_API_URL
