export const PEOPLE_SEARCH_REQUEST = 'PEOPLE_SEARCH_REQUEST';
export const PEOPLE_SEARCH_SUCCESS = 'PEOPLE_SEARCH_SUCCESS';
export const PEOPLE_SEARCH_FAILURE = 'PEOPLE_SEARCH_FAILURE';

export const PERSON_REQUEST = 'PERSON_REQUEST';
export const PERSON_SUCCESS = 'PERSON_SUCCESS';
export const PERSON_FAILURE = 'PERSON_FAILURE';

export const SAVE_PERSON_REQUEST = 'SAVE_PERSON_REQUEST';
export const SAVE_PERSON_SUCCESS = 'SAVE_PERSON_SUCCESS';
export const SAVE_PERSON_FAILURE = 'SAVE_PERSON_FAILURE';

export const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST';
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';

export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';

export const PEOPLE_ROOT_URL = process.env.REACT_APP_API_URL
